FROM --platform=linux/amd64 ubuntu:18.04

# List of softwares with version
ARG bwa_version=0.7.17
ARG freebayes_version=1.3.6
ARG gatk_version=4.2.6.0
ARG picard_version=2.27.4
ARG fastqc_version=0.11.9
ARG samtools_version=1.14
ARG bedtools_version=2.26.0
ARG cutadapt_version=4.4
ARG rtgtools_version=3.12.1


# building updates essencials
RUN apt-get update && apt-get install -y \
 wget \
 git \
 build-essential \
 ssh \
 openssh-server \
 vim

# Installing conda enviroment
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-Linux-x86_64.sh && \
 bash Miniconda3-py39_23.1.0-1-Linux-x86_64.sh -p /miniconda -b  && \
 rm Miniconda3-py39_23.1.0-1-Linux-x86_64.sh

#set the conda environment
ENV PATH="/miniconda/bin:$PATH"

# Install all softwares needed
RUN conda install -c bioconda -c conda-forge gatk4=${gatk_version} \
    freebayes=${freebayes_version} \
    picard=${picard_version} \
    bwa=${bwa_version} \
    fastqc=${fastqc_version} \
    samtools=${samtools_version} \
    bedtools=${bedtools_version} \
    cutadapt=${cutadapt_version} \
    rtg-tools=${rtgtools_version}


# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
